//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EL_PublicHoliday
    {
        public int EL_PHID { get; set; }
        public Nullable<System.DateTime> EL_HolidayDate { get; set; }
        public string EL_HolidayRemark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<short> IsReverse { get; set; }
        public short IsTrueHoliday { get; set; }
        public Nullable<short> IsWeekend { get; set; }
    }
}
