//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPMEntities3 : DbContext
    {
        public BPMEntities3()
            : base("name=BPMEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
      
        public DbSet<EL_MasterData> EL_MasterData { get; set; }
        public DbSet<EL_MasterDataDetails> EL_MasterDataDetails { get; set; }
        public DbSet<EL_PublicHoliday> EL_PublicHoliday { get; set; }
    }
}
